#! /bin/bash

do_verify(){
	./verify_all.sh
}

do_compose_message(){
	echo ========; ./ricm -r risky -i bugfix xxx
}

do_verify && 
    (do_compose_message) && 
    (echo; echo ========; echo; git status)
