#! /bin/bash

do_verify(){
	./verify_all.sh
}


do_compose_message(){
	echo ========
	 ./ricm -r risky -i bugfix xxx
}


do_git_status(){
	echo
	echo ========
	echo
	git status
}


main(){
	do_verify && 
	    do_compose_message && 
	        do_git_status
}


main
