#! /bin/bash

do_verify(){
	./verify_all.sh sh
	./verify_all.sh py
}


do_compose_sample_risky_bugfix_message(){
	echo ========
	 ./ricm.sh -r risky -i bugfix xxx | pbcopy
	 pbpaste
}


do_git_status(){
	echo
	echo ========
	echo
	git status
}


main(){
    do_verify && 
        do_compose_sample_risky_bugfix_message && 
        do_git_status
}


main
