#!/bin/bash

space=' '
dash='-'

warn() {
    echo "$*" >&2
}


parse_args() {
  while getopts "r:i:" opt; do
    case $opt in
      r)
        risk="$OPTARG"
        ;;
      i)
        intent="$OPTARG"
        ;;
      \?)
        echo "Invalid option: -$OPTARG" >&2
        exit 1
        ;;
    esac
  done
  shift $((OPTIND-1))
  
  message="$*"
  
  # warn "Risk: $risk"
  # warn "Message: $message"
}


function risk_code {
    case $1 in
	safe)      echo -n '.' ;;
	validated) echo -n '^' ;;
	risky)     echo -n '!' ;;
	broken)    echo -n '@' ;;

	*)         echo -n ' ' ;;
    esac
}


function intent_code {
    case $1 in
	feature)       echo -n 'f' ;;
	bugfix)        echo -n 'b' ;;
	refactoring)   echo -n 'r' ;;
	documentation) echo -n 'd' ;;

	*)             echo -n ' ' ;;
    esac	
}


main() {
    local risk=

    parse_args "$@"
    
    # Validate args...
    if [[ "${risk}" == '' ]] 
    then
	warn 'Undefined risk.  Specify with -r flag.'
	exit 1
    fi

    if [[ "${intent}" == '' ]] 
    then
	warn 'Undefined intent.  Specify with -i flag.'
	exit 1
    fi

    if [[ "${message}" == '' ]]
    then
	warn 'Undefined message.'
	exit 1
    fi

    risk_code="$(risk_code $risk)"
    intention_code="$(intent_code $intent)"

    echo "${risk_code}${space}${intention_code}${space}${message}"
}


main "$@"
