#! /bin/bash

verify_sh="$HOME/repos/ApprovalTests.shell/bash/verify.sh"

function verify_fn(){
    bash ${verify_sh} "$*" -d 'meld'
}

ricm_path=$(PATH=.:$PATH which ricm)


for risk in safe validated risky broken
do
    for intention in feature bugfix refactoring documentation
    do
	test_name="${risk}-${intention}"
	message="Message generated by: ${ricm_path} -r '${risk}'  -i '${intention}'"
	
	${ricm_path} -r "${risk}"  -i "${intention}"  "${message}"
    done
done | verify_fn -tall_risks_all_intentions


{
    ${ricm_path}                        Command line missing -r flag 2>&1 
    ${ricm_path} -r risk                Command line missing -i flag 2>&1 
    ${ricm_path} -r risk -i refactoring                              2>&1 
} | verify_fn -t malformed_command_line
